name: test

on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      # https://github.com/actions/checkout/issues/217
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pull all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install, build, and test
        env:
          HUSKY_SKIP_INSTALL: 1
        run: |
          npm install
          npm run build-changed
          npm run test-changed
