name: test

on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-18.04
    container: node:10.16-jessie
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install, build, and test
        env:
          HUSKY_SKIP_INSTALL: 1
        run: |
          yarn install
          yarn build-changed
          yarn test-changed
# test
